name: Delay API CI
on:
  push:
    branches:
      - 'main'
      - 'develop'
      - 'release/**'
      - 'bug/**'
      - 'feature/**'
  pull_request:
    branches: [ develop, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Use Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install python requirements
      run: pip install -r requirements.txt

    - name: Run model-test
      run: make model-test

    - name: Run api-test
      run: make api-test